[V3 bugfix] Change private methods to public ones (#4205)
<!-- Thanks for submitting a pull request! We appreciate you spending
the time to work on these changes. Please follow the template so that
the reviewers can easily understand what the code changes affect. -->

## Summary

<!-- Explain the motivation for this PR. Include "Fixes #<number>" if
applicable. -->

This issue:
https://github.com/software-mansion/react-native-reanimated/issues/4135
describes an error happening on old Android versions.
The error message is
> 🚫 ${\color{red}\text{Error}}$
> Exception in HostFunction: java.lang.NoSuchMethodError: no non-static
method
"Lcom/swmansion/reanimated/NativeProxy;.registerEventHandler(Lcom/swmansion/reanimated/nativeProxy/EventHandler;)V",
js engine: hermes

It can be simply fixed by changing some function from `private` to
`public` ones as suggested
[here](https://github.com/software-mansion/react-native-reanimated/issues/4135#issuecomment-1463572593).

Fixes #4135

## Test plan

<!-- Provide a minimal but complete code snippet that can be used to
test out this change along with instructions how to run it and a
description of the expected behavior. -->
Tested on android simulator

Co-authored-by: Aleksandra Cynk <aleksandracynk@Aleksandras-MacBook-Pro.local>