Auto-workletize functions passed to runOnUI (#4459)
## Summary

This PR adds `runOnUI` to the list of automatically workletized
functions as suggested by @kacperkapusciak.

Previously, the following code:

```tsx
runOnUI(() => {
  console.log('Hello from the UI thread!');
})();
```

would throw the following error:

```
Error: runOnUI() can only be used on worklets, js engine: hermes
```

because the function passed to `runOnUI` needs to be marked as worklet:

```diff
 runOnUI(() => {
+  'worklet';
   console.log('Hello from the UI thread!');
 })();
```

After this change, the `'worklet';` directive can be omitted and the
function will be automatically workletized by the Reanimated Babel
plugin.

## Test plan

<details>
<summary>App.tsx</summary>

```tsx
import { Button, StyleSheet, View } from 'react-native';

import React from 'react';
import { runOnUI } from 'react-native-reanimated';

export default function App() {
  const handlePress = () => {
    runOnUI(() => {
      console.log('Hello from the UI thread!');
    })();
  };

  return (
    <View style={styles.container}>
      <Button title="Click me" onPress={handlePress} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

</details>