Fix monorepo-CI (#4636)
## Summary

Current main CI is broken because of:
```
/Users/runner/work/react-native-reanimated/react-native-reanimated/monorepo/RootApp/node_modules/react-native-reanimated/ios/LayoutReanimation/REASnapshot.m:87:38: use of undeclared identifier 'RCTView'
_values[@"borderRadius"] = @(((RCTView *)view).borderRadius);
```
This PR try to resolve this issue by adding `RCTView.h` import. What is
strange the problem exists only in monorepo.
## Test plan

See CI status

![image](https://github.com/software-mansion/react-native-reanimated/assets/36106620/9faa6187-be9a-48fa-bb84-f8a4c9256d7c)