Keep non-react views in AnimationManager (#4439)
<!-- Thanks for submitting a pull request! We appreciate you spending
the time to work on these changes. Please follow the template so that
the reviewers can easily understand what the code changes affect. -->

## Summary

<!-- Explain the motivation for this PR. Include "Fixes #<number>" if
applicable. -->
Removing views with id -1 (views that are not a react-native ones)
causes at least two bugs on Android.

Fixes #4306 and Fixes #4437

### Bug
https://github.com/software-mansion/react-native-reanimated/issues/4306
- [Android] <Animated.ScrollView /> is crashing on navigate.goBack()
when using refreshControl prop

<details><summary> Error log </summary>

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.swmansion.reanimated.example, PID: 14673
    java.lang.IndexOutOfBoundsException: getChildDrawingOrder() returned invalid index 1 (child count is 1)
        at android.view.ViewGroup.getAndVerifyPreorderedIndex(ViewGroup.java:2099)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4287)
        at android.view.View.draw(View.java:23197)
        at android.view.View.updateDisplayListIfDirty(View.java:22061)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)
        at android.view.View.draw(View.java:23197)
        at android.view.View.updateDisplayListIfDirty(View.java:22061)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)
        at android.view.View.updateDisplayListIfDirty(View.java:22052)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)
        at android.view.View.updateDisplayListIfDirty(View.java:22052)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)
        at android.view.View.updateDisplayListIfDirty(View.java:22052)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:22052)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:22052)
        at android.view.View.draw(View.java:22925)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:22052)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
E/AndroidRuntime:     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22017)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4670)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4381)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3600)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9087)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
        at android.view.Choreographer.doCallbacks(Choreographer.java:899)
        at android.view.Choreographer.doFrame(Choreographer.java:832)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
</details>
<table>
<tr><td>BEFORE</td><td>AFTER</td></tr>
<tr><td>


https://user-images.githubusercontent.com/56199675/237047814-3f54fef7-b546-44a4-ba6b-a184c39b792e.mov

</td><td>


https://user-images.githubusercontent.com/56199675/237047543-afb5c935-6e2a-4b1d-9c70-42ed1d6ca9ef.mov

</td></tr>
</table>

### Bug
https://github.com/software-mansion/react-native-reanimated/issues/4437
- ReanimatedError: Exception in HostFunction:
java.lang.ClassNotFoundException: Could not retrieve ViewPager2
instance, js engine: reanimated

No error logs 😢 
<table>
<tr><td>BEFORE</td><td>AFTER</td></tr>
<tr><td>



https://user-images.githubusercontent.com/56199675/237048938-faeea75c-786c-42de-a607-9b681769ee7f.mov



</td><td>



https://user-images.githubusercontent.com/56199675/237048461-1b2c87ee-bb0a-4649-8a20-60b8a4811a93.mov



</td></tr>
</table>

## Test plan

<!-- Provide a minimal but complete code snippet that can be used to
test out this change along with instructions how to run it and a
description of the expected behavior. -->
Tested on following repos:
* https://github.com/vozaldi/repro-rn-reanimated-crash
* https://github.com/ealmiladi/reanimated-exiting-bug

---------

Co-authored-by: Aleksandra Cynk <aleksandracynk@swmansion.com>