[0.80] Fix "error: method resolve in class LengthPercentage cannot be applied to given types" (#7413)
## Summary

This PR fixes the following error while trying to build
react-native-reanimated with react-native 0.80 for Android by removing
`BorderRadiiDrawableUtils` and `ReactNativeUtils` as they are unused:

```
reanimated/BorderRadiiDrawableUtils.java:21: error: method resolve in class LengthPercentage cannot be applied to given types;
> Task :react-native-reanimated:compileDebugJavaWithJavac FAILED
    return length.resolve(bounds.width(), bounds.height()).toPixelFromDIP().getHorizontal();
                 ^
  required: float
  found:    int,int
  reason: actual and formal argument lists differ in length
```

Note that building with RN 0.80 for Android also requires
https://github.com/software-mansion/react-native-reanimated/pull/7409.

## Test plan