Resolve headers name conflict with expo-dev-client (#5010)
## Summary

The `Check Expo dev-client nightly build` CI
(https://github.com/software-mansion/react-native-reanimated/actions/runs/6016772546)
fails with error:
```bash
❌  /Users/runner/work/react-native-reanimated/react-native-reanimated/app/
node_modules/react-native-reanimated/Common/cpp/ReanimatedRuntime/
WorkletRuntimeDecorator.cpp:59:3: use of undeclared identifier 'jsi_utils'

  jsi_utils::installJsiFunction(
```

This PR fixes the issue of header name conflict with expo-dev-client.
The Expo package includes its own JsiUtils.h file, which leads to a
collision in header mapping within Xcode. To resolve this problem, we
have three possible options:
- Use an absolute import path (doesn't work on Android).
- Rename JsiUtils.h (as done in this PR).
- Utilize namespace imports like #include <Reanimated/...>.

In the past we encountered similar issue with Xcode flat header mapping
- https://github.com/software-mansion/react-native-reanimated/pull/1775

Fixes
https://github.com/software-mansion/react-native-reanimated/issues/5002

## Test plan

Check CI status:
https://github.com/software-mansion/react-native-reanimated/actions/runs/6034169391?pr=5010