tests: add missing mock function (#5755)
## Summary

<!-- Explain the motivation for this PR. Include "Fixes #<number>" if
applicable. -->
This PR adds a missing mock, to avoid the error `TypeError: (0 ,
_reactnativereanimated.scrollTo) is not a function` when executing tests
on jest.