Fix V8 integration for Reanimated V3 (#3736)
This PR is an attempt to fix V8 integration with Reanimated V3. Current issue:

```
react-native/node_modules/react-native-reanimated/Common/cpp/ReanimatedRuntime/ReanimatedRuntime.cpp:40:38: error: use of undeclared identifier 'runtime_'
```

Updated `ReanimatedRuntime::make` to accept a new parameter `jsi::Runtime *runtime`, which is necessary to initialize V8

- Create a new RN app
- Setup the app to have V8 as engine
- Enable the new architecture (might not be necessary)
- Build the Android app
- Confirm the app builds and runs fine with this change

<!--
Please include code that can be used to test this change and short description how this example should work.
This snippet should be as minimal as possible and ready to be pasted into editor (don't exclude exports or remove "not important" parts of reproduction example)
-->

- [ ] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Added TS types tests
- [ ] Added unit / integration tests
- [ ] Updated documentation
- [ ] Ensured that CI passes