Fix proc types
This commit fixes regression introduced in #959 (f5eaf18) by utilizing Parameters and ReturnType types from TS.
Function args type are `any[]` which will make TS infer them.

Previous implementation was failing with error:
```
node_modules/react-native-reanimated/react-native-reanimated.d.ts:237:36 - error TS2314: Generic type 'Adaptable' requires 1 type argument(s).
```
because Adaptable generic type was not specialized.

References:
https://www.typescriptlang.org/docs/handbook/utility-types.html#parameterst
https://www.typescriptlang.org/docs/handbook/utility-types.html#returntypet