Fix undefined `config` in podspec (#5390)
## Summary

This PR fixes error:
```bash
[!] Invalid `Podfile` file: 
[!] Invalid `RNReanimated.podspec` file: undefined local variable or method `config' for Pod:Module
Did you mean?  concerning.

 #  from /Users/runner/work/react-native-reanimated/react-native-reanimated/Example/node_modules/react-native-reanimated/RNReanimated.podspec:90
 #  -------------------------------------------
 #    gcc_debug_definitions =  "$(inherited)"
 >    if config[:react_native_minor_version] >= 73 || !is_release
 #      gcc_debug_definitions << " HERMES_ENABLE_DEBUGGER=1"
 #  -------------------------------------------
.

 #  from /Users/runner/work/react-native-reanimated/react-native-reanimated/Example/ios/Podfile:31
 #  -------------------------------------------
 #  target 'ReanimatedExample' do
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
 ```

Related to PRs: https://github.com/software-mansion/react-native-reanimated/pull/5383 and https://github.com/software-mansion/react-native-reanimated/pull/5334

It is because we renamed `config` to global variable `$config`

## Test plan

Build Example app

---------

Co-authored-by: Tomek Zawadzki <tomasz.zawadzki@swmansion.com>